// =============================================================================
// ESOPT UI CONFIGURATION
// -----------------------------------------------------------------------------
// This file defines DISPLAY/UI metadata only. The actual trained model
// (feature list, category vocabulary, and linear-SVM weights) lives in
// js/model_weights.js (MODEL_WEIGHTS), auto-generated by
// matlab/generate_features_and_export_weights.m.
//
// Each modality lists the MATLAB column/feature names (matching
// MODEL_WEIGHTS.features) that belong to it, in display order.
//
// SCALING TO NEW EPILEPSY TYPES / MODALITIES
// - New epilepsy type: add a key to MODEL_VERSIONS with its own `modalities`
//   array and `status: "active"` (plus a matching MODEL_WEIGHTS export).
// - New modality/feature for an existing type: add an entry to that type's
//   `modalities` array — the UI and scoring engine are fully data-driven.
// =============================================================================

const MODEL_VERSIONS = {
  MTLE: {
    label: "Mesial Temporal Lobe Epilepsy (MTLE)",
    status: "active",
    modalities: [
      { id: "seizureType", name: "Type of Seizures", features: ["Seizures"] },
      {
        id: "semiology",
        name: "Semiology",
        features: ["First_symptom_main", "Rest_of_the_symptoms_main", "Postictal_symptom"]
      },
      { id: "interictalSEEG", name: "Interictal SEEG", features: ["Spike_dist", "Gamma_dist", "SPM"] },
      { id: "mri", name: "MRI Findings", features: ["MRI1", "MRI2", "MRI3"] }
    ]
  },

  // Placeholder slots for future scale-up (disabled in the UI for now).
  TLE_NEOCORTICAL: { label: "Temporal Neocortical Epilepsy", status: "coming_soon" },
  FLE: { label: "Frontal Lobe Epilepsy", status: "coming_soon" },
  GENERALIZED: { label: "Generalized Epilepsy", status: "coming_soon" }
};

// Friendly display name + numeric-input hints per MATLAB feature name.
const FEATURE_DISPLAY = {
  Seizures: { label: "Seizure Type" },
  First_symptom_main: { label: "First Symptom" },
  Rest_of_the_symptoms_main: { label: "Rest of the Symptoms" },
  Postictal_symptom: { label: "Postictal Symptoms" },
  Spike_dist: { label: "Abnormality Spike Distance", step: 0.01, placeholder: "e.g., 0.35" },
  Gamma_dist: { label: "Abnormal Spike-Gamma Distance", step: 0.01, placeholder: "e.g., 0.35" },
  SPM: { label: "Spatial Perturbation Map (SPM)", step: 0.01, placeholder: "e.g., 0.60" },
  MRI1: { label: "Presence of Lesion" },
  MRI2: { label: "Region of Interest" },
  MRI3: { label: "Lobe of Interest" }
};

// Optional friendly labels for raw category codes coming from MODEL_WEIGHTS.
// Any component not listed here is shown as-is (title-cased fallback).
const CATEGORY_LABELS = {
  Seizures: {
    FBTC: "Focal to Bilateral Tonic-Clonic (FBTC)",
    FIA: "Focal Impaired Awareness (FIA)",
    FA: "Focal Aware (FA)"
  },
  MRI1: {
    lesional: "Lesional",
    "abnormal non-lesional": "Abnormal Non-Lesional",
    normal: "Normal",
    "uncertain lesion": "Uncertain Lesion"
  },
  MRI2: {
    mesiotemporal: "Mesiotemporal",
    "mesiotemporal and neocortical": "Mesiotemporal and Neocortical",
    neocortical: "Neocortical",
    "normal/unspecific": "Unspecific/Normal"
  },
  MRI3: {
    temporal: "Temporal",
    extratemporal: "Extratemporal",
    both: "Temporal and Extratemporal",
    uncertain: "Uncertain/Unspecific"
  },
  Postictal_symptom: {
    "Autonomic signs": "Autonomic Signs",
    Headache: "Headache",
    "Language Dysfunction": "Language Dysfunction",
    "Nose wiping": "Nose Wiping",
    "Psychiatric signs": "Psychiatric Signs",
    Unresponsiveness: "Unresponsiveness"
  },
  First_symptom_main: {
    "Affective (emotional) phenomena": "Affective (Emotional)",
    "Autonomic phenomena": "Autonomic",
    "Cognitive phenomena": "Cognitive",
    "Complex motor phenomena": "Complex Motor",
    "Sensory phenomena": "Sensory"
  },
  Rest_of_the_symptoms_main: {
    "Affective (emotional) phenomena": "Affective (Emotional)",
    "Autonomic phenomena": "Autonomic",
    "Cognitive phenomena": "Cognitive",
    "Complex motor phenomena": "Complex Motor",
    "Elementary motor phenomena": "Elementary Motor",
    "Sensory phenomena": "Sensory"
  },
  NA: "Not documented / NA"
};

// Features rendered as checkboxes (multiple categories selectable at once),
// matching MATLAB's comma-separated multi-hot encoding. All other text
// features are rendered as single-select dropdowns.
const MULTI_SELECT_FEATURES = new Set([
  "Seizures",
  "First_symptom_main",
  "Rest_of_the_symptoms_main",
  "Postictal_symptom"
]);
