// AUTO-GENERATED by train_and_export_model.m -- do not hand-edit.
// Linear-SVM per feature, trained once on all patients.
const MODEL_WEIGHTS = {
  "meta": {
    "generated_on": "06-Oct-2026 15:12:07",
    "n_patients": 57,
    "n_good": 39,
    "n_poor": 18,
    "source": "trained_once_on_all_data",
    "score_note": "p = 1/(1+exp(-s)), s = sum(beta.*((x-mu)./sigma)) + bias; positive class = Good outcome",
    "scoring": "feature p -> mean per modality -> mean across modalities",
    "cutoff_sens80": 0.43162042115269306,
    "cutoff_sens80_fpr": 0.33333333333333331,
    "cutoff_note": "Computed on training-set scores (optimistic). Replace with the LOSO-derived cutoff if available."
  },
  "feature_names": [
    "Spike_dist",
    "Gamma_dist",
    "SPM",
    "Seizures",
    "MRI1",
    "MRI2",
    "MRI3",
    "Postictal_symptom",
    "First_symptom_main",
    "Rest_of_the_symptoms_main"
  ],
  "feature_types": [
    "numeric",
    "numeric",
    "numeric",
    "multi_cat",
    "single_cat",
    "single_cat",
    "single_cat",
    "multi_cat",
    "multi_cat",
    "multi_cat"
  ],
  "group_of_feature": [
    1,
    1,
    1,
    2,
    3,
    3,
    3,
    4,
    4,
    4
  ],
  "modality_names": [
    "EEG_SPM",
    "Seizures",
    "MRI",
    "Symptoms"
  ],
  "modality_members": [
    [
      "Spike_dist",
      "Gamma_dist",
      "SPM"
    ],
    [
      "Seizures"
    ],
    [
      "MRI1",
      "MRI2",
      "MRI3"
    ],
    [
      "Postictal_symptom",
      "First_symptom_main",
      "Rest_of_the_symptoms_main"
    ]
  ],
  "vocabs": [
    [],
    [],
    [],
    [
      "FA",
      "FBTC",
      "FIA"
    ],
    [
      "abnormal non-lesional",
      "lesional",
      "normal",
      "uncertain lesion"
    ],
    [
      "mesiotemporal",
      "mesiotemporal and neocortical",
      "neocortical",
      "normal/unspecific"
    ],
    [
      "both",
      "extratemporal",
      "temporal",
      "uncertain"
    ],
    [
      "Autonomic signs",
      "Headache",
      "Language Dysfunction",
      "NA",
      "Nose wiping",
      "Psychiatric signs",
      "Unresponsiveness"
    ],
    [
      "Affective (emotional) phenomena",
      "Autonomic phenomena",
      "Cognitive phenomena",
      "Complex motor phenomena",
      "Missing",
      "Sensory phenomena"
    ],
    [
      "Affective (emotional) phenomena",
      "Autonomic phenomena",
      "Cognitive phenomena",
      "Complex motor phenomena",
      "Elementary motor phenomena",
      "Sensory phenomena"
    ]
  ],
  "features": {
    "Spike_dist": {
      "type": "numeric",
      "beta": -0.79879286472714739,
      "bias": 0.071823247401543222,
      "mu": 33.726473576754955,
      "sigma": 9.7964991681565188,
      "raw_threshold": 34.607323186827351,
      "direction": -1
    },
    "Gamma_dist": {
      "type": "numeric",
      "beta": -0.76888691940443787,
      "bias": 0.042647920507576209,
      "mu": 33.481777730791073,
      "sigma": 9.17849216506749,
      "raw_threshold": 33.99088198833055,
      "direction": -1
    },
    "SPM": {
      "type": "numeric",
      "beta": 0.7060284079190815,
      "bias": -0.076571814363842666,
      "mu": 0.43763697015376513,
      "sigma": 0.27425385588293805,
      "raw_threshold": 0.46738097918469246,
      "direction": 1
    },
    "Seizures": {
      "type": "multi_cat",
      "beta": [
        0.9153801827304946,
        5.7463403242863365E-5,
        -4.4408920985006262E-16
      ],
      "bias": -0.42304556905543445,
      "mu": [
        0.28846153846153838,
        0.56196581196581186,
        0.94871794871794857
      ],
      "sigma": [
        0.45771632723969269,
        0.50125902870275929,
        0.22284582877119641
      ]
    },
    "MRI1": {
      "type": "single_cat",
      "beta": [
        0.13263134390476267,
        0.58882335970419253,
        -0.39706522983615311,
        -0.31969247678578427
      ],
      "bias": -0.021360130750158617,
      "mu": [
        0.012820512820512815,
        0.47649572649572636,
        0.33547008547008539,
        0.17521367521367517
      ],
      "sigma": [
        0.11365904860851628,
        0.50459492373465775,
        0.47702091836374433,
        0.38406787452344487
      ]
    },
    "MRI2": {
      "type": "single_cat",
      "beta": [
        -0.24882644385185759,
        0.41099469931948551,
        0.43527836539052656,
        -0.2348798155169225
      ],
      "bias": -0.66241069219420856,
      "mu": [
        0.49572649572649558,
        0.079059829059829029,
        0.089743589743589716,
        0.33547008547008539
      ],
      "sigma": [
        0.50513492586558717,
        0.27261321250251375,
        0.28875987704037659,
        0.47702091836374433
      ]
    },
    "MRI3": {
      "type": "single_cat",
      "beta": [
        0.19283735757157888,
        0.45675959855681914,
        -0.15170354469467773,
        -0.14488488189855875
      ],
      "bias": -0.82060017745537461,
      "mu": [
        0.012820512820512815,
        0.0769230769230769,
        0.57478632478632463,
        0.33547008547008539
      ],
      "sigma": [
        0.11365904860851628,
        0.269215789246157,
        0.4994707747351852,
        0.47702091836374433
      ]
    },
    "Postictal_symptom": {
      "type": "multi_cat",
      "beta": [
        9.8860192406513558E-5,
        1.4604655529215638E-5,
        0.93805319873404336,
        0.655996549181648,
        -0.50998292196236039,
        0.38860710880588961,
        7.7725396321559614E-5
      ],
      "bias": -0.19235037494680168,
      "mu": [
        0.040598290598290586,
        0.066239316239316212,
        0.314102564102564,
        0.11965811965811961,
        0.068376068376068355,
        0.03846153846153845,
        0.66666666666666652
      ],
      "sigma": [
        0.1993918369507659,
        0.25126324765426644,
        0.46894141227910646,
        0.32790649949058431,
        0.25499146098118053,
        0.19428976048920787,
        0.4762631714777007
      ]
    },
    "First_symptom_main": {
      "type": "multi_cat",
      "beta": [
        -0.32773788703928763,
        0.44195898690984081,
        0.24207090662265038,
        -0.25465254303522245,
        -0.49327107383356639,
        0.292586956310144
      ],
      "bias": 0.15806399234534402,
      "mu": [
        0.096153846153846118,
        0.38461538461538447,
        0.0769230769230769,
        0.055555555555555539,
        0.26923076923076911,
        0.11752136752136748
      ],
      "sigma": [
        0.29784056292375849,
        0.49151853535558976,
        0.269215789246157,
        0.23142230351441095,
        0.44813176486907735,
        0.3253597112993622
      ]
    },
    "Rest_of_the_symptoms_main": {
      "type": "multi_cat",
      "beta": [
        -0.40870562082477035,
        0.25117951611162104,
        -0.73116345015643547,
        0.17805739944745058,
        3.6669174532377724E-5,
        0.40986449701752925
      ],
      "bias": 0.039301766435136755,
      "mu": [
        0.20299145299145291,
        0.49145299145299132,
        0.36538461538461525,
        0.85256410256410242,
        0.48076923076923062,
        0.079059829059829029
      ],
      "sigma": [
        0.40637185555278454,
        0.50507956760216144,
        0.48650093953052154,
        0.35819407409281417,
        0.50477960483654438,
        0.27261321250251369
      ]
    }
  }
};
